### ISSUE TITLE
hehe

### ISSUE THREAD

**Issue by Vikashgathala** [the-r3aper7/the-r3aper7#1]
sai baby ese kya kr rhe ho khaali repo bna k chhod rkhi hai. bss yahi issue aaya hai abhitk to baaki kuch aur nahi hai

**Comment by the-r3aper7** [comment]
khali nahi hai github ka special feature hai jab apne naam ka repo bana ke readme file banate hai tho tab yeh sab apne profile page pe aata hai

**Comment by Vikashgathala** [comment]
pataa hai baby lekin kuch code ka jalwa to dikhao apna

**Comment by the-r3aper7** [comment]
private karke rakha hai
